name: DynamicProxy CI

on:
  pull_request:
    paths: ['src/**']

jobs:
  DynamicProxy-CI:

    runs-on: ubuntu-latest
    env:
      working-directory: ./src

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.*

    - name: Install dependencies      
      run: dotnet restore
      working-directory: ${{env.working-directory}}
    - name: Build     
      run: dotnet build --configuration Release
      working-directory: ${{env.working-directory}}
    - name: Test
      run: dotnet test
      working-directory: ${{env.working-directory}}
