name: DynamicProxy NuGet

on:
  push:
    branches: [ release ]

    paths: [src/Castle.DynamicProxy.DependencyInjection/**]

jobs:
  Castle-DynamicProxy-NuGet:

    runs-on: windows-2019
    env:
      working-directory: ./src/Castle.DynamicProxy.DependencyInjection
      package-name: Castle.DynamicProxy.DependencyInjection

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.*

    - name: Install dependencies      
      run: dotnet restore
      working-directory: ${{env.working-directory}}

    - name: Build     
      run: dotnet build --configuration Release --no-restore
      working-directory: ${{env.working-directory}}

    - name: Test
      run: dotnet test --no-restore
      working-directory: ${{env.working-directory}}

    - name: Pack NuGet package
      run: dotnet pack -c Release
      working-directory: ${{env.working-directory}}

    - name: Publish NuGet package
      run: dotnet nuget push **/${{env.package-name}}.*.nupkg --skip-duplicate
      working-directory: ${{env.working-directory}}
